import os
import random
os.system('cls' if os.name == 'nt' else 'clear') # Recommended by poke on stack overflow: (https://stackoverflow.com/questions/2084508/clear-the-terminal-in-python)

console_screenHeader = """
Python Refresher App by Cameron Godwin (2024) v1.0


============================================="""
console_screenMainMenu = """Welcome to the Python Refresher App!
=============================================


   What would you like to do?

   [1] Name tricks: Some cool string and array tricks with your inputted name
   [2] BMI Calculator: Calculate your BMI based on your height and weight
   [3] The Five Number Report: A report of the five numbers inputted
   [4] The Anogram Finder: Check if two words are anograms of each other
   [5] Leap Year Checker: Check if a year is a leap year
   [6] Basic Calculator: Perform basic calculations
   [7] First 10 Fibonacci Numbers: Generate the first 10 Fibonacci numbers
   [8] Prime Number Checker: Check if a number is prime using a loop
   [9] Multiplication Table: Generate a multiplication table for numbers 1 - 10
   [10] Palindrome Checker: Check if a word is a palindrome
   [11] Banking section: Perform basic banking operations
   [12] Sort names by score: Sort names and scores from a file
   [13] To-Do List Manager: Manage your to-do tasks
   [14] Movie Ticket Reservation System: Reserve tickets for movies

   [0] Exit app.
"""
console_screenTemplate = """=============================================




   [0] Exit app.
"""

# Generated by chatGPT: ======
def sort_names_by_score():
    try:
        # Read the file and store names and scores in a list
        with open('names_scores.txt', 'r') as file:
            lines = file.readlines()

        # Create a list of tuples (name, score) from the file content
        name_score_list = []
        for line in lines:
            name, score = line.strip().split(",")
            name_score_list.append((name, int(score)))

        # Sort the list by score in descending order
        sorted_list = sorted(name_score_list, key=lambda x: x[1], reverse=True)

        # Write the sorted list to a new file
        with open('sorted_scores.txt', 'w') as sorted_file:
            for name, score in sorted_list:
                sorted_file.write(f"{name},{score}\n")

        print("Scores sorted and written to sorted_scores.txt")
    except FileNotFoundError:
        print("The file names_scores.txt was not found.")
    except Exception as e:
        print(f"An error occurred: {e}")

# File to store to-do tasks
TODO_FILE = 'todo_list.txt'

def load_tasks():
    """Load tasks from the file into a list."""
    if os.path.exists(TODO_FILE):
        with open(TODO_FILE, 'r') as file:
            tasks = [line.strip() for line in file.readlines()]
    else:
        tasks = []
    return tasks

def save_tasks(tasks):
    """Save the task list to the file."""
    with open(TODO_FILE, 'w') as file:
        for task in tasks:
            file.write(task + "\n")
    input("Press enter to continue...")
    todo_manager()

def add_task(task, tasks):
    """Add a new task to the list."""
    tasks.append(task)
    save_tasks(tasks)
    print(f"Task '{task}' added.")
    input("Press enter to continue...")
    todo_manager()

def view_tasks(tasks):
    """Display all tasks."""
    if tasks:
        print("\nYour To-Do List:")
        for idx, task in enumerate(tasks, start=1):
            print(f"{idx}. {task}")
        print("")
        print("")
    else:
        print("No tasks available.")
        input("Press enter to continue...")
        todo_manager()
    

def remove_task(task_number, tasks):
    """Mark a task as completed (remove it from the list)."""
    try:
        task = tasks.pop(task_number - 1)
        save_tasks(tasks)
        print(f"Task '{task}' completed and removed from the list.")
        input("Press enter to continue...")
    except IndexError:
        print("Invalid task number.")

def todo_manager():
    tasks = load_tasks()
    os.system('cls' if os.name == 'nt' else 'clear')
    print(console_screenHeader)
    print("To-Do List Manager")
    print(console_screenTemplate)

    while True:
        print("   [1] Add task")
        print("   [2] View all tasks")
        print("   [3] Mark task as completed")
        print("")
        print("")

        choice = input("Enter your choice: ")

        if choice == "1":
            os.system('cls' if os.name == 'nt' else 'clear')
            print(console_screenHeader)
            print("To-Do List Manager - Adding new Task...")
            print(console_screenTemplate)
            task = input("Enter the new task: ")
            add_task(task, tasks)


        elif choice == "2":
            os.system('cls' if os.name == 'nt' else 'clear')
            print(console_screenHeader)
            print("To-Do List Manager - Viewing all Tasks...")
            print(console_screenTemplate)
            view_tasks(tasks)

        elif choice == "3":
            os.system('cls' if os.name == 'nt' else 'clear')
            print(console_screenHeader)
            print("To-Do List Manager - Marking task as completed...")
            print(console_screenTemplate)
            view_tasks(tasks)
            try:
                task_number = int(input("Enter the number of the task to mark as completed: "))
                remove_task(task_number, tasks)
            except ValueError:
                print("Please enter a valid number.")

        elif choice == "0":
            print("Exiting To-Do List Manager.")
            main()

        else:
            print("Invalid choice. Please try again.")
            input("Press enter to continue...")
            os.system('cls' if os.name == 'nt' else 'clear')

# File to store reservations
RESERVATIONS_FILE = 'reservations.txt'

# List of movies and their available seats
movies = [
    {"name": "Deadpool", "available_seats": 50},
    {"name": "Chuck Noris", "available_seats": 30},
    {"name": "The Bee Movie", "available_seats": 20}
]

def load_reservations():
    """Load current reservations and update available seats accordingly."""
    if os.path.exists(RESERVATIONS_FILE):
        with open(RESERVATIONS_FILE, 'r') as file:
            reservations = [line.strip().split(',') for line in file.readlines()]
        
        # Deduct reserved seats from the corresponding movies
        for reservation in reservations:
            name, movie, tickets = reservation
            tickets = int(tickets)
            for m in movies:
                if m["name"] == movie:
                    m["available_seats"] -= tickets
    else:
        reservations = []
    return reservations

def save_reservation(name, movie, tickets):
    """Save a new reservation to the file."""
    with open(RESERVATIONS_FILE, 'a') as file:
        file.write(f"{name},{movie},{tickets}\n")

def display_movies():
    """Display the available movies and their remaining seats."""
    os.system('cls' if os.name == 'nt' else 'clear')
    print(console_screenHeader)
    print("Movie Ticket Reservation System - all movies")
    print(console_screenTemplate)
    print("\nAvailable Movies:")
    for idx, movie in enumerate(movies, start=1):
        print(f"{idx}. {movie['name']} (Available seats: {movie['available_seats']})")
    print()

def select_movie():
    """Allow the user to select a movie."""
    try:
        choice = int(input("Enter the number corresponding to the movie: "))
        if 1 <= choice <= len(movies):
            return movies[choice - 1]
        else:
            print("Invalid choice. Please select a valid movie.")
            return None
    except ValueError:
        print("Please enter a valid number.")
        return None

def movie_reservation_system():
    os.system('cls' if os.name == 'nt' else 'clear')
    print(console_screenHeader)
    print("Movie Ticket Reservation System")
    print(console_screenTemplate)

    load_reservations()
    
    while True:
        print("   [1] View available movies")
        print("   [2] Make a reservation")
        print("")
        print("")

        choice = input("Enter your choice: ")

        if choice == "1":
            display_movies()

        elif choice == "2":
            display_movies()
            selected_movie = select_movie()
            if selected_movie:
                try:
                    tickets_requested = int(input("How many tickets would you like to reserve? "))
                    if tickets_requested <= selected_movie["available_seats"]:
                        name = input("Enter your name: ")
                        selected_movie["available_seats"] -= tickets_requested
                        save_reservation(name, selected_movie["name"], tickets_requested)
                        print(f"Reservation confirmed! {tickets_requested} ticket(s) reserved for {name}.")
                    else:
                        print(f"Sorry, only {selected_movie['available_seats']} tickets are available.")
                except ValueError:
                    print("Please enter a valid number of tickets.")
        
        elif choice == "0":
            print("Exiting Movie Ticket Reservation System.")
            break
        
        else:
            print("Invalid choice. Please try again.")
# ============================


def main():
    os.system('cls' if os.name == 'nt' else 'clear')
    try:
        print(console_screenHeader)
        print(console_screenMainMenu)
        menuOption = input("Enter the corresponding number: ")
        if menuOption == "1":
            os.system('cls' if os.name == 'nt' else 'clear')
            print(console_screenHeader)
            print("Name Tricks")
            print(console_screenTemplate)
            Firstname = input("Enter your name (first): ")
            if Firstname == "0":
                print("Exiting app...")
                exit()
            elif Firstname == "":
                print("Please enter a name.")
                Firstname = input("")
            else:
                print("Great! Now enter your last name or just hit enter to continue.")
                Lastname = input("Enter your name (last): ")
                if Lastname == "":
                    Lastname = " "
                else:
                    os.system('cls' if os.name == 'nt' else 'clear')
                    print(console_screenHeader)
                    print("Name Tricks - Results")
                    print(console_screenTemplate)
                    print("Here's what I was able to do with the name(s) you gave me: " + Firstname + " " + Lastname)
                    print("1. Your name in uppercase: " + Firstname.upper() + " " + Lastname.upper())
                    print("2. Your name in lowercase: " + Firstname.lower() + " " + Lastname.lower())
                    print("3. Your name reversed: " + Firstname[::-1] + " " + Lastname[::-1])
                    shuffled_firstname = ''.join(random.sample(Firstname, len(Firstname)))
                    shuffled_lastname = ''.join(random.sample(Lastname, len(Lastname)))
                    print("4. Your name with letters in random order: " + shuffled_firstname + " " + shuffled_lastname)
                    input("Press enter to continue...")
                    main()
       
        if menuOption == "2":
            os.system('cls' if os.name == 'nt' else 'clear')
            print(console_screenHeader)
            print("BMI Calculator")
            print(console_screenTemplate)
            height = float(input("Enter your height in centimeters: "))
            if height == 0:
                print("Exiting app...")
                exit()
            weight = float(input("Enter your weight in kilograms: "))
            if weight == 0:
                print("Exiting app...")
                exit()
            bmi = weight / ((height/100) ** 2)
            print("Your BMI is: ", round(bmi, 2))
            if bmi < 18.5:
                print("You are underweight.")
            elif 18.5 <= bmi < 24.9:
                print("You are normal weight.")
            elif 25 <= bmi < 29.9:
                print("You are overweight.")
            elif 30 <= bmi < 34.9:
                print("You are obese.")
            elif bmi >= 35:
                print("You are extremely obese.")
            input("Press enter to continue...")
            main()

        if menuOption == "3":
            os.system('cls' if os.name == 'nt' else 'clear')
            print(console_screenHeader)
            print("The Five Number Report")
            print(console_screenTemplate)
            number1 = int(input("Enter the first number: "))
            number2 = int(input("Enter the second number: "))
            number3 = int(input("Enter the third number: "))
            number4 = int(input("Enter the fourth number: "))
            number5 = int(input("Enter the fifth number: "))
            numbers = [number1, number2, number3, number4, number5]
            print("The numbers you entered are: ", numbers)
            print("The smallest number is: ", min(numbers))
            print("The largest number is: ", max(numbers))
            print("The range of the numbers is: ", max(numbers) - min(numbers))
            print("The sum of the numbers is: ", sum(numbers))
            print("The product of all the numbers is: ", number1 * number2 * number3 * number4 * number5)
            print("The mean of the numbers is: ", sum(numbers) / len(numbers))
            print("The numbers in ascending order are: ", sorted(numbers))
            print("The numbers in descending order are: ", sorted(numbers, reverse=True))
            input("Press enter to continue...")
            main()

        if menuOption == "4":
            os.system('cls' if os.name == 'nt' else 'clear')
            print(console_screenHeader)
            print("The Anogram Finder")
            print(console_screenTemplate)
            word1 = input("Enter the first word: ")
            if word1 == "0":
                print("Exiting app...")
                exit()
            word2 = input("Enter the second word: ")
            if word2 == "0":
                print("Exiting app...")
                exit()
            if sorted(word1) == sorted(word2):
                print("")
                print("")
                print("The words are anagrams of each other.")
                print("")
                print("Here's a sorted view: Word one - ",sorted(word1), " Word two - ", sorted(word2))
                
            else:
                print("")
                print("")
                print("The words are not anagrams of each other.")
                print("")
                print("Here's a sorted view: Word one - ",sorted(word1), " Word two - ", sorted(word2))
            input("Press enter to continue...")
            main()

        if menuOption == "5":
            os.system('cls' if os.name == 'nt' else 'clear')
            print(console_screenHeader)
            print("Leap Year Checker")
            print(console_screenTemplate)
            year = int(input("Enter the year you want to check: "))
            if year == 0:
                print("Exiting app...")
                exit()
            if year % 4 == 0:
                if year % 100 == 0:
                    if year % 400 == 0:
                        print("The year", year, "is a leap year.")
                    else:
                        print("The year", year, "is not a leap year.")
                else:
                    print("The year", year, "is a leap year.")
            else:
                print("The year", year, "is not a leap year.")
            input("Press enter to continue...")
            main()

        if menuOption == "6":
            os.system('cls' if os.name == 'nt' else 'clear')
            print(console_screenHeader)
            print("Basic Calculator")
            print(console_screenTemplate)
            num1 = float(input("Enter the first number: "))
            if num1 == 0:
                print("Exiting app...")
                exit()
            operator = input("Enter the operator (+, -, *, /): ")
            if operator == "0":
                print("Exiting app...")
                exit()
            num2 = float(input("Enter the second number: "))
            if num2 == 0:
                print("Exiting app...")
                exit()
            if operator == "+":
                print(num1, "+", num2, "=", num1 + num2)
            elif operator == "-":
                print(num1, "-", num2, "=", num1 - num2)
            elif operator == "*":
                print(num1, "*", num2, "=", num1 * num2)
            elif operator == "/":
                if num2 == 0:
                    print("You cannot divide by zero.")
                else:
                    print(num1, "/", num2, "=", num1 / num2)
            else:
                print("Invalid operator. Please try again.")
            input("Press enter to continue...")
            main()
        
        if menuOption == "7":
            os.system('cls' if os.name == 'nt' else 'clear')
            print(console_screenHeader)
            print("First 10 Fibonacci Numbers")
            print(console_screenTemplate)
            n1 = 0
            n2 = 1
            count = 0
            while count < 10:
                print(n1)
                nth = n1 + n2
                n1 = n2
                n2 = nth
                count += 1
            input("Press enter to continue...")

        if menuOption == "8":
            os.system('cls' if os.name == 'nt' else 'clear')
            print(console_screenHeader)
            print("Prime Number Checker")
            print(console_screenTemplate)
            number = int(input("Enter the number you want to check: "))
            if number == 0:
                print("Exiting app...")
                exit()
            if number > 1:
                for i in range(2, number):
                    if (number % i) == 0:
                        print(number, "is not a prime number.")
                        break
                else:
                    print(number, "is a prime number.")
            else:
                print(number, "is not a prime number.")
            input("Press enter to continue...")
            main()
        
        if menuOption == "9":
            os.system('cls' if os.name == 'nt' else 'clear')
            print(console_screenHeader)
            print("Multiplication Table")
            print(console_screenTemplate)
            print("   [1] Generated table (less neat)")
            print("")
            print("")
            print("       |   1   |   2   |   3   |   4   |   5   |   6   |   7   |   8   |   9   |   10  ")
            print("----------------------------------------------------------------------------------------")
            print("   1  ||   1   |   2   |   3   |   4   |   5   |   6   |   7   |   8   |   9   |   10  ")
            print("   2  ||   2   |   4   |   6   |   8   |  10   |  12   |  14   |  16   |  18   |   20  ")
            print("   3  ||   3   |   6   |   9   |  12   |  15   |  18   |  21   |  24   |  27   |   30  ")
            print("   4  ||   4   |   8   |  12   |  16   |  20   |  24   |  28   |  32   |  36   |   40  ")
            print("   5  ||   5   |  10   |  15   |  20   |  25   |  30   |  35   |  40   |  45   |   50  ")
            print("   6  ||   6   |  12   |  18   |  24   |  30   |  36   |  42   |  48   |  54   |   60  ")
            print("   7  ||   7   |  14   |  21   |  28   |  35   |  42   |  49   |  56   |  63   |   70  ")
            print("   8  ||   8   |  16   |  24   |  32   |  40   |  48   |  56   |  64   |  72   |   80  ")
            print("   9  ||   9   |  18   |  27   |  36   |  45   |  54   |  63   |  72   |  81   |   90  ")
            print("  10  ||  10   |  20   |  30   |  40   |  50   |  60   |  70   |  80   |  90   |  100  ")
            print("")
            print("")
            choice = input("Press enter to continue...")
            if choice == "0":
                print("Exiting app...")
                exit()
            elif choice == "1":
                os.system('cls' if os.name == 'nt' else 'clear')
                print(console_screenHeader)
                print("Multiplication Table")
                print(console_screenTemplate)
                for i in range(1, 11):
                    for j in range(1, 11):
                        print(i * j, end="\t")
                    print()
                input("Select an option:")
            else :
                main()
        
        if menuOption == "10":
            os.system('cls' if os.name == 'nt' else 'clear')
            print(console_screenHeader)
            print("Palindrome Checker")
            print(console_screenTemplate)
            word = input("Enter the word you want to check: ")
            if word == "0":
                print("Exiting app...")
                exit()
            if is_palindrome(word):
                print(word, "is a palindrome.")
            else:
                print(word, "is not a palindrome.")
            input("Press enter to continue...")
            main

        if menuOption == "11":
            bankingSection()
            
        if menuOption == "12":
            os.system('cls' if os.name == 'nt' else 'clear')
            print(console_screenHeader)
            print("Sort names by score")
            print(console_screenTemplate)
            sort_names_by_score()
            option = input("Press enter to continue...")
            if option == "0":
                print("Exiting app...")
                exit()
            else:
               main()

        if menuOption == "13":
            todo_manager()
            option = input("Press enter to continue...")
            if option == "0":
                print("Exiting app...")
                exit()
            else:
                main()
        
        if menuOption == "14":
            movie_reservation_system()
            option = input("Press enter to continue...")
            if option == "0":
                print("Exiting app...")
                exit()
            else:
                main()

        elif menuOption == "0":
            print("Exiting app...")
            exit()
        else:
            print("Invalid input. Please try again.")
            print("If you wish to exit the app, press 'CTRL + C' on your keyboard or select exit from the main menu.")
            input("Press enter to continue...")
            main()



    except Exception as e:
        print("An error occurred: ", e)
        print("If you wish to exit the app, press 'CTRL + C' on your keyboard or select exit from the main menu.")
        input("Press enter to continue...")
        main()



main()

def is_palindrome(word):
    if word == word[::-1]:
        return True
    else:
        return False

def bankingSection():
    os.system('cls' if os.name == 'nt' else 'clear')
    print(console_screenHeader)
    print("Banking Section")
    print(console_screenTemplate)
    print("   [1] Check Account Balance")
    print("   [2] Deposit")
    print("   [3] Withdraw")
    bankingOption = input("Enter the corresponding number: ")
    if bankingOption == "0":
        print("Returning to main menu...")
        main()
    if bankingOption == "1":
        os.system('cls' if os.name == 'nt' else 'clear')
        print(console_screenHeader)
        print("Account Balance")
        print(console_screenTemplate)
        balance = 0
        print("Your account balance is: ", balance)
        input("Press enter to continue...")
        bankingSection()
    elif bankingOption == "2":
        os.system('cls' if os.name == 'nt' else 'clear')
        print(console_screenHeader)
        print("Deposit")
        print(console_screenTemplate)
        deposit = float(input("Enter the amount you want to deposit: "))
        if deposit == 0:
            print("Exiting app...")
            exit()
        balance += deposit
        print("You deposited: ", deposit)
        print("Your new balance is: ", balance)
        input("Press enter to continue...")
        bankingSection()
    elif bankingOption == "3":
        os.system('cls' if os.name == 'nt' else 'clear')
        print(console_screenHeader)
        print("Withdraw")
        print(console_screenTemplate)
        withdraw = float(input("Enter the amount you want to withdraw: "))
        if withdraw == 0:
            print("Exiting app...")
            exit()
        if withdraw > balance:
            print("Insufficient funds.")
        else:
            balance -= withdraw
            print("You withdrew: ", withdraw)
            print("Your new balance is: ", balance)
        input("Press enter to continue...")
        main()
    else:
        print("Invalid input. Please try again.")
        print("If you wish to exit the app, press 'CTRL + C' on your keyboard or select exit from the main menu.")
        input("Press enter to continue...")
        bankingSection()

def exit():
    print("Exiting app...")


